FORMAT: 1A
HOST: https://api.societyicon.com/v1

# Society Icon API

## Authentication

Society Icon's API uses the [OAuth 2.0 protocol](http://tools.ietf.org/html/draft-ietf-oauth-v2-12) for simple, but effective authentication and authorization.

Society Icon's API requires that you authenticate to use the API. Authentication can be made as a client or as a user. User authentication is only needed when making request specifically on the behalf of a user. When Authentication is made an access token is given. These tokens are unique to a client or user and should be stored securely. Access tokens may expire at any time in the future.

## HTTP Headers

For authentication the *Authorization* header is used. A client specifies the header as `Authorization: Bearer <access token>`

The response content type is specified by the *Accept* header. For example a client can specify that the response should use JSON encoded by using the `Accept: application/json` request header.

*gzip* compression is supported. A client can specify that gzip responses can be handled using the `Accept-Encoding: gzip` request header.

<!-- include(authorization.apib) -->
<!-- include(ads.apib) -->
<!-- include(users.apib) -->