# Group Products

## Paragraphs [/products/paragraphs]

#### Get paragraphs [GET]

List all available paragraphs types for product descriptions. 

+ Response 200 (application/json)

    + Body

            {"paragraphs":[{"id":1,"title":"Beskrivning","sorting":1},{"id":2,"title":"S\u00e4ljtips","sorting":2}]}
