# Group Users

## Get Users [/users{email}]
#### Get Users [GET]

+ Parameters

    + email: `antongildebrand@gmail.com` (required, string) - Search for users with this email

+ Response 200 (application/json)
    
        {  
           "user":{  
              "id":39,
              "first_name":"Anton",
              "last_name":"Gildebrand",
              "email":"antongildebrand@gmail.com"
           }
        }

+ Response 200 (application/json)

        {
            "user": null
        }


## Create User [/users]
#### Create User [POST]

+ Request (application/json)

        {
            "user": {
                "email": "123hjnagdfnjk@asdgnjsd.com"
            },
            "organization": {
                "id": 9
            }
        }

+ Response 200 (application/json)
    
        {  
           "user":{  
              "id":39,
              "first_name":"Anton",
              "last_name":"Gildebrand",
              "email":"antongildebrand@gmail.com"
           }
        }

+ Response 200 (application/json)

        {
            "user": {
                "id":91,
                "first_name":null,
                "last_name":null,
                "email":"123hjnagdfnjk@asdgnjsd.com"
            }
        }